version: '3.8'  # 指定 Docker Compose 文件的版本
services:
  postgres:
    image: postgres:latest  # 使用官方的 PostgreSQL 镜像
    container_name: postgres_container  # 为容器指定一个名称
    environment:
      POSTGRES_DB: mydatabase  # 设置数据库名
      POSTGRES_USER: user  # 设置数据库用户
      POSTGRES_PASSWORD: password  # 设置数据库用户密码
    ports:
      - "5432:5432"  # 将容器的 5432 端口映射到宿主机的 5432 端口
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 持久化数据存储
    networks:
      - backend

volumes:
  postgres_data:  # 定义一个名为 postgres_data 的数据卷

networks:
  backend:  # 定义一个名为 backend 的网络